[theme]
primaryColor = "#CC0000"
backgroundColor = "#0D0D0D"
secondaryBackgroundColor = "#1A1A1A"
textColor = "#FFD700"
font = "sans serif"

[server]
headless = false
port = 8501

[browser]
gatherUsageStats = false
